import Head from 'next/head'
import Image from 'next/image'
import FoodList from '../components/FoodList'
import CocktailsList from '../components/FoodList'
import SearchBlock from '../components/SearchBlock'
import style from '../styles/Home.module.scss'

const Home = () => {
  return (
    <div className={style.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SearchBlock/>
      </div>

      <FoodList/>
        

    </div>
  )
}

export default Home
